# Generated by Django 4.1.7 on 2023-03-04 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dj_puro', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModelName',
            new_name='Category',
        ),
    ]
